name: Run tests

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-github:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-22.04]
          julia-version: ['lts']
          julia-arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
